triggers:
  - github:
      version: 2
      entryPoint: default
      conditions:
        type: push
        payload:
          ref:  "^(?!^\\/refs\\/tags\\/$).*$"

flows:
  default:
    - log: "!!!"
