triggers:
  - github:
      version: 2
      entryPoint: default
      conditions:
        type: push
        branch: ".*"
        payload:
          ref: "refs/tags/.*"

flows:
  default:
    - log: "123"
